[build]
  publish = "dist"
  command = "npx @11ty/eleventy"
  functions = "netlify/functions"

[dev]
  command = "npx @11ty/eleventy --serve"
  targetPort = 8080
  port = 8888
  publish = "dist"
  jwtRolePath = "app_metadata.authorization.roles"
  jwtSecret = "REPLACE_ME_WITH_YOUR_SECRET"

[[redirects]]
  from = "/success"
  to = "/success/"
  status = 200

[forms."notation-submission"]
  success_url = "/success"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"